name: education_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #for Web Instead Of using dar:html that will cause crash when run on Mobile
  universal_html: ^2.2.4

  #localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  provider: ^6.1.1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.6.0
  iconly: ^1.0.1
  lottie: ^3.0.0

  get_it: ^7.6.7

  shared_preferences: ^2.2.2

  smooth_page_indicator: ^1.1.0
  swipe_to: ^1.0.5

  path_provider: ^2.1.2
  open_file: ^3.3.2
  url_launcher: ^6.2.4

  image_picker: ^1.0.7
  file_picker: ^6.1.1

  dartz: ^0.10.1
  equatable: ^2.0.5

  #  youtube_metadata: ^1.0.1
  video_thumbnail: ^0.5.3

  #video Player
  chewie: ^1.7.4


  #Json Annotation
  json_annotation: ^4.8.1

  #Class Mapper
  smartstruct: ^1.4.0

  #Firebase Auth
  firebase_auth: ^4.16.0

  firebase_ui_auth: ^1.12.1

  firebase_storage: ^11.6.0

  cloud_firestore: ^4.14.0

  firebase_core: ^2.24.2

  firebase_crashlytics: ^3.4.9

  #GoRouter
  go_router: ^13.0.1

  #Database
  floor: ^1.4.2

  #Connection Listener
  connectivity_plus: ^5.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.1.5
  flutter_lints: ^3.0.1
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

  #For Auto .g file generation used by json_serializable & floor & retrofit
  #You have to declare [part .g.dart] for the required file
  #Use [dart run build_runner build] Comanned to generate
  build_runner: ^2.4.8

  #Json Annotation
  json_serializable: ^6.7.1

  #Mapper classes generator
  smartstruct_generator: ^1.4.0


  firebase_auth_mocks: ^0.13.0
  google_sign_in_mocks: ^0.3.0
  fake_cloud_firestore: ^2.4.8
  firebase_storage_mocks: ^0.6.1
  firebase_app_check: ^0.2.1+8

  #DataBase Entity Tables class generator
  floor_generator: ^1.4.2

flutter:
  #used for localization
#  generate: true
  uses-material-design: true

  assets:
    - assets/vectors/
    - assets/images/
    - assets/lottie/
    - assets/icons/
    - assets/database/
    - assets/translations/

  fonts:
    - family: Aeonik
      fonts:
        - asset: assets/fonts/aeonik/AeonikTRIAL-Bold.otf
          weight: 700
        - asset: assets/fonts/aeonik/AeonikTRIAL-BoldItalic.otf
          style: italic
          weight: 700
        - asset: assets/fonts/aeonik/AeonikTRIAL-Light.otf
          weight: 300
        - asset: assets/fonts/aeonik/AeonikTRIAL-LightItalic.otf
          style: italic
          weight: 300
        - asset: assets/fonts/aeonik/AeonikTRIAL-Regular.otf
          weight: 400
        - asset: assets/fonts/aeonik/AeonikTRIAL-RegularItalic.otf
          style: italic
          weight: 400
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
