// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGBfO_EkHQFkeYrS3M3g-ka95tgTmBmx8',
    appId: '1:744361439511:web:4961a7519e2dc9fcb48752',
    messagingSenderId: '744361439511',
    projectId: 'flutter-tdd-educationapp',
    authDomain: 'flutter-tdd-educationapp.firebaseapp.com',
    storageBucket: 'flutter-tdd-educationapp.appspot.com',
    measurementId: 'G-D1SK818F4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs_jJKrhRLJciqyD49Xwq3QmcXN4fJ2pE',
    appId: '1:744361439511:android:08b3ad7fcf822f67b48752',
    messagingSenderId: '744361439511',
    projectId: 'flutter-tdd-educationapp',
    storageBucket: 'flutter-tdd-educationapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-xaVJewIjq7aJv2oOopik-zw0Tc9qajk',
    appId: '1:744361439511:ios:606a3bd17232f584b48752',
    messagingSenderId: '744361439511',
    projectId: 'flutter-tdd-educationapp',
    storageBucket: 'flutter-tdd-educationapp.appspot.com',
    iosBundleId: 'com.dbestech.educationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-xaVJewIjq7aJv2oOopik-zw0Tc9qajk',
    appId: '1:744361439511:ios:66758ce0c2d4d3dcb48752',
    messagingSenderId: '744361439511',
    projectId: 'flutter-tdd-educationapp',
    storageBucket: 'flutter-tdd-educationapp.appspot.com',
    iosBundleId: 'com.dbestech.educationApp.RunnerTests',
  );
}
