// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'localization_mapper.dart';

// **************************************************************************
// MapperGenerator
// **************************************************************************

class LocalizationMapperImpl extends LocalizationMapper {
  LocalizationMapperImpl() : super();

  @override
  LocalizationEntity getLocalizationEntityFromModel(LocalizationModel model) {
    final localizationentity = LocalizationEntity(
      autoGeneratedId: model.autoGeneratedId,
      id: model.id,
      screenName: model.screenName,
      viewType: model.viewType,
      textCode: model.textCode,
      text: model.text,
      languageCode: model.languageCode,
    );
    return localizationentity;
  }

  @override
  LocalizationModel getLocalizationModelFromEntity(LocalizationEntity entity) {
    final localizationmodel = LocalizationModel(
      autoGeneratedId: entity.autoGeneratedId,
      id: entity.id,
      screenName: entity.screenName,
      viewType: entity.viewType,
      textCode: entity.textCode,
      text: entity.text,
      languageCode: entity.languageCode,
    );
    return localizationmodel;
  }
}
