// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'localization_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

LocalizationModel _$LocalizationModelFromJson(Map<String, dynamic> json) =>
    LocalizationModel(
      autoGeneratedId: json['autoGeneratedId'] as int?,
      id: json['id'] as String?,
      screenName: json['screenName'] as String?,
      viewType: json['viewType'] as String?,
      textCode: json['textCode'] as String?,
      text: json['text'] as String?,
      languageCode: json['languageCode'] as String?,
    );

Map<String, dynamic> _$LocalizationModelToJson(LocalizationModel instance) =>
    <String, dynamic>{
      'autoGeneratedId': instance.autoGeneratedId,
      'id': instance.id,
      'screenName': instance.screenName,
      'viewType': instance.viewType,
      'textCode': instance.textCode,
      'text': instance.text,
      'languageCode': instance.languageCode,
    };
